# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: So that I don't forget
#email: your-email@example.com
description: More than just coding. Hopefully. 
author: Jan Wychowaniak
url: https://janwychowaniak.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # "" # the subpath of your site, e.g. /blog
github_username:  janwychowaniak

permalink: /:categories/:title.html

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
